version: '3'
services:
    db:
      image: mysql:5
      ports:
        - "3307:3306"
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_USER: 'root'
      volumes:
        - ./data/mysqlSf:/var/lib/mysql

    maildev:
        image: djfarrelly/maildev
        ports:
          - "8002:80"


    php:
        build: .docker
        ports:
          - "8080:80"
        volumes:
            - ./:/var/www
