version: '3'
services:
    php:
        build: .docker
        volumes:
            - .:/var/www/app
        ports:
            - "8000:80"
        depends_on:
            - db
            - mailhog
        user: www-data
    db:
        image: mysql:5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: 'root'
        # volumes:
        #     - .docker/data/mysqlSf:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"