version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/app
        ports:
            - 8000:80
        depends_on:
            - php
            - db
    php:
        build: .docker
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/app
        user: www-data

    db:
        image: mysql:5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: 'root'
        # volumes:
        #     - ./data/mysqlSf:/var/lib/mysql