version: '3'
services:
    db:
      image: mysql:5
      ports:
        - "3307:3306"
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_USER: 'root'
      # volumes:
      #   - ./data/mysqlSf:/var/lib/mysql

    php:
        build: .docker
        ports:
          - "8000:80"
        volumes:
            - ./:/var/www/app
        depends_on:
            - db
            - mailhog
        user: www-data

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"