version: '3'
services:
    wp:
        build: .docker
        ports:
            - "8000:80"
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DEBUG=1
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/wp-content/themes/docker-theme
            # - .docker/volumes/plugins:/var/www/html/wp-content/plugins
            # - .docker/volumes/uploads:/var/www/html/wp-content/uploads
        user: www-data
        
    db:
        image: mysql:5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - .docker/volumes/data/mysqlSf:/var/lib/mysql